Repository MRita443/AedAirTransport, pull requests merged in 2023-01, with the labels that each got.

#2 Menu
  .gitignore
  .idea/misc.xml
  CMakeLists.txt
  src/CMakeLists.txt
  src/airline.cpp
  src/main.cpp
  src/menu.cpp
  src/menu.h
Labels: documentation, enhancement

#3 Added function for position distance
  src/position.cpp
  src/position.h
Labels: enhancement

#4 Hashes
  CMakeLists.txt
  src/airline.cpp
  src/airline.h
  src/airport.cpp
  src/airport.h
  src/dataRepository.cpp
  src/dataRepository.h
  src/graph.cpp
  src/graph.h
  src/menu.cpp
  src/menu.h
Labels: documentation, enhancement

#5 Added airport information functions
  .idea/.gitignore
  .idea/AirTransport.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/dataRepository.cpp
  src/dataRepository.h
  src/graph.cpp
  src/graph.h
  src/menu.cpp
Labels: documentation, enhancement

#6 Added util functions and checks
  src/dataRepository.cpp
  src/dataRepository.h
  src/graph.cpp
  src/graph.h
  src/menu.cpp
  src/position.cpp
  src/position.h
Labels: documentation, enhancement

#9 Flight output
  src/graph.cpp
  src/graph.h
  src/menu.cpp
Labels: bug, documentation, enhancement

#10 Extras
  .gitignore
  build/.cmake/api/v1/query/client-vscode/query.json
  build/CMakeCache.txt
  build/CMakeFiles/cmake.check_cache
  src/graph.cpp
  src/graph.h
Labels: documentation, functionalities
